# Generated by Django 2.0.2 on 2019-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0004_auto_20190702_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
